Updated identity.VerifyPassword to return a identity model if success…
ONSdigital/dp-identity-api-archived pull request #34
Opened 2018-10-03 08:14 UTC by daiLlew

- Updated `VevrifyPassword()` to return the identity model when successful.
- Updated necessary tests.
- Add more godoc to various packages.

2018-10-03 13:53 UTC, eldeal requested changes

2018-10-03 13:53 UTC, eldeal commented on api/token.go
> +	_, err := api.IdentityService.VerifyPassword(ctx, tokenReq.Email, tokenReq.Password)
If we're only returning an error, this function call could be inlined with the if statement, which I believe we do most often than not in other services

2018-10-03 13:53 UTC, eldeal commented on encryption/service.go
> +// Encryption provides functionality for encrypting an comparing password values. The Service struct implements
`and` not `an`

2018-10-03 13:53 UTC, eldeal commented on encryption/service.go
> +// CompareHashAndPassword generate a password. See https://godoc.org/golang.org/x/crypto/bcrypt#CompareHashAndPassword
feels like a copy paste error - 'generate a password'?

2018-10-03 13:53 UTC, eldeal commented on identity/models.go
> +	// ErrInvalidArguments the required fields with empty or invalid
'were' not 'with'?

2018-10-03 13:53 UTC, eldeal commented on identity/models.go
> +	// ErrAuthenticateFailed authentication was unsuccessful
I think this would read more smoothly as 'AuthenticationFailed' but not a major issue if thats just me

2018-10-03 13:53 UTC, eldeal commented on identity/service.go
> +//Create create a new user identity, returns ErrInvalidArguments if the required fields are invalid,
dont need 'create' twice at start of comment

2018-10-03 13:53 UTC, eldeal commented on identity/service.go
> +// VerifyPassword verify if the password provided is correct the email provided. Returns the active identity with the
Feel like the first sentence of this comment doesnt grammar?

2018-10-04 09:15 UTC, daiLlew commented on api/token.go
> +	_, err := api.IdentityService.VerifyPassword(ctx, tokenReq.Email, tokenReq.Password)
As it is now we are only returning the error. I updated this method to return the identity as it will be needed in the next set of changes I am making. I want to keep the PRs as small and focused as possible which is why I am doing this separate from the next change.

2024-10-04 13:38 UTC, janderson2 commented
Repo is archived. Closing

2024-10-04 13:38 UTC, closed without merging